# Generated by Django 4.2.1 on 2023-05-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repo_role",
            fields=[
                (
                    "role_name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("manageTask_permission", models.BooleanField()),
                ("manageUser_permission", models.BooleanField()),
                ("manageUserRole_permission", models.BooleanField()),
                ("role_priority", models.PositiveSmallIntegerField()),
            ],
            options={"db_table": "tms_repo_role",},
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                ("repo_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
            options={"db_table": "tms_repository",},
        ),
        migrations.CreateModel(
            name="Repo_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repository.repository",
                    ),
                ),
                (
                    "role_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repository.repo_role",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
            options={"db_table": "tms_repo_user",},
        ),
    ]
