# Generated by Django 4.2.1 on 2023-05-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo_role',
            old_name='can_add_people',
            new_name='can_manage_users',
        ),
        migrations.RemoveField(
            model_name='repo_role',
            name='can_assign_task',
        ),
    ]
