# Generated by Django 4.2.1 on 2023-05-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='repo_user',
            name='unique_un_role_constraint',
        ),
        migrations.RenameField(
            model_name='repo_user',
            old_name='user',
            new_name='rp_user',
        ),
        migrations.AddConstraint(
            model_name='repo_user',
            constraint=models.UniqueConstraint(fields=('rp_user', 'role'), name='unique_un_role_constraint'),
        ),
    ]
