# Generated by Django 4.2.1 on 2023-05-26 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repository', '0002_rename_can_add_people_repo_role_can_manage_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo_role',
            name='repo_users',
        ),
        migrations.CreateModel(
            name='Repo_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.repo_role')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tms_repo_user',
            },
        ),
    ]
