# Generated by Django 4.2.1 on 2023-05-31 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_remove_repo_user_unique_un_role_constraint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo_role',
            old_name='can_manage_task',
            new_name='can_manage_tasks',
        ),
    ]
