# Generated by Django 4.2.1 on 2023-05-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_remove_repo_role_repo_users_repo_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='repo_user',
            constraint=models.UniqueConstraint(fields=('username', 'role_id'), name='unique_un_role_constraint'),
        ),
    ]
