# Generated by Django 4.2.1 on 2023-05-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task_assignment',
            name='unique_un_task_constraint',
        ),
        migrations.RenameField(
            model_name='task_assignment',
            old_name='user',
            new_name='ass_user',
        ),
        migrations.AddConstraint(
            model_name='task_assignment',
            constraint=models.UniqueConstraint(fields=('ass_user', 'task'), name='unique_un_task_constraint'),
        ),
    ]
