# Generated by Django 4.2.1 on 2023-05-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_status_taskstatushistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskStatusHistory',
            new_name='Task_status_history',
        ),
    ]
