# Generated by Django 4.2.1 on 2023-05-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_taskstatushistory_task_status_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_status_history',
            name='task_id',
            field=models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
